# Generated by Django 2.2.5 on 2020-01-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_etiqueta_usuario_usuarioartista_usuarioetiquetaartista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
