# Generated by Django 2.2.5 on 2020-01-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200107_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='pictureUrl',
            field=models.URLField(null=True, verbose_name='Url de la imagen'),
        ),
    ]
