# Generated by Django 2.2.5 on 2019-12-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191128_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Debe introducir un nombre', verbose_name='Nombre')),
                ('fechaInicio', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(null=True, verbose_name='Fecha Fin')),
                ('precio', models.TextField(help_text='Debe introducir un precio, o gratis', verbose_name='Precio')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Lenguaje')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Municipio')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Tipo')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuaciones',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idPelicula',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ocupacion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='lenguaje',
            field=models.ManyToManyField(to='main.Lenguaje'),
        ),
        migrations.AddField(
            model_name='evento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Municipio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo'),
        ),
    ]
