# Generated by Django 2.1.2 on 2019-04-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Categoría')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('nombre', models.TextField(unique=True, verbose_name='Ocupación')),
                ('ocupacionId', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.TextField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(verbose_name='Título')),
                ('fechaEstreno', models.DateField(null=True, verbose_name='Fecha de Estreno')),
                ('imdbUrl', models.URLField(verbose_name='URL en IMDB')),
                ('categorias', models.ManyToManyField(to='main.Categoria')),
            ],
            options={
                'ordering': ('titulo', 'fechaEstreno'),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Regular'), (4, 'Buena'), (5, 'Muy Buena')], verbose_name='Puntuación')),
                ('idPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pelicula')),
            ],
            options={
                'ordering': ('puntuacion',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.TextField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(help_text='Debe introducir una edad numérica mayor a 14 años', verbose_name='Edad')),
                ('sexo', models.CharField(help_text='Debe elegir entre M o F', max_length=1, verbose_name='Sexo')),
                ('codigoPostal', models.TextField(verbose_name='Código Postal')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ocupacion')),
            ],
            options={
                'ordering': ('idUsuario',),
            },
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuaciones',
            field=models.ManyToManyField(through='main.Puntuacion', to='main.Usuario'),
        ),
    ]
