# Generated by Django 2.1.2 on 2018-11-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Tu comentario', verbose_name='Comentario')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Receta')),
            ],
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
    ]
